sudo: required
services:
  - docker

before_install:
  - docker build -t chunyeel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chunyeel/docker-react npm run test -- --coverage


